### PR TITLE
Fix door hinges

### PR DESCRIPTION
**Pull request by zedwick**
Adds support for door hinges.

### CODE REVIEW

**Comment by Gerrygames** [comment]
@ForceUpdate1 had some changes, which were not pushed to this repository. Could you adapt your code to the new changes?

**Comment by zedwick** [comment]
Updated. I like the new code, far happier about the quality of this submission now too.

**Comment by Gerrygames** [comment]
Thanks ;)

**Comment by ForceUpdate1** [comment]
http://screen.forceupdate1.de/11-29-27.png

**Comment by zedwick** [comment]
That seems to happen when placing a door against the side of grass. Placing the door against the top side of the block does place the door, replacing the grass. The same happens no matter which direction/side it is placed. Checking with a 1.12.2 client, you cannot place a door on the side of grass, only on top of it.

**Comment by ForceUpdate1** [comment]
Is it possible to fix that ?

**Comment by zedwick** [comment]
I'm not sure. The impression I get is that the top half of the door is client-side, not sent by viaversion. I think it would need to send a block update to refresh the block above where the player tried to place the door for the client, but I'm not sure where to go about putting that in to viaversion. Not quite as easy as changing some blockstate values :)

**Pull request merged**
